let API_URL;
switch (process.env.REACT_APP_ENVIRONMENT) {
	case 'production':
		API_URL = {
			HOMESCREEN_DATA: 'https://78gzqx2cqf.execute-api.us-east-1.amazonaws.com/Prod/getHomescreenData',
			LOGIN: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/login`, //Not using
			CREATE_NOTE: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/noteboard`, //Not using
			UPDATE_NOTE: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/noteboard`, //Not using
			REMOVE_NOTE: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/remove-note`, //Not using
			GET_NOTES: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/noteboard`, //Not using
			GET_NOTELABELS: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/notelabels`, //Not using
			SAVE_NOTELABELS: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/notelabels`, //Not using
			PATIENT_SEARCH: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/patientSearch',
			PATIENT_BY_ID: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/getPatient', //Not using
			GET_ALL_CITY: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getAllCityList',
			OPENTASKSLIST: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/openTasks',
			COMPLETE_TASKS: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/completeBulkTasks',
			// GET_PATIENT_DOCUMENT:
			// 'https://lo66l03g8f.execute-api.us-east-1.amazonaws.com/Prod/getPatientTimelineDatadev',
			GET_PATIENT_DOCUMENT:
				'https://udwa9duxej.execute-api.us-east-1.amazonaws.com/Prod/GetPatientTimeline',
			// GET_FINALIZED_EXAM: 'https://fcuh32hzr1.execute-api.us-east-1.amazonaws.com/Prod/getfinalizedExam',
			ADD_PATIENT: 'https://6wciednm8i.execute-api.us-east-1.amazonaws.com/Prod/addPatientInfo',
			UPDATE_PATIENT: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/updatePtientInfo',
			RESET_PATIENT_PASSWORD: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/resetPatientPass',
			PATIENT_PORTAL_DATA: 'https://le1we4r3mh.execute-api.us-east-1.amazonaws.com/Prod/patientPortalData',
			SEND_PATIENT_PORTAL_ACCESS:
				'https://le1we4r3mh.execute-api.us-east-1.amazonaws.com/Prod/sendPatientAccessMail',
			GET_DOCUMENT_TYPE: 'https://21vyk11t77.execute-api.us-east-1.amazonaws.com/Prod/getDocumentList',
			UPLOAD_DOCUMENT: 'https://21vyk11t77.execute-api.us-east-1.amazonaws.com/Prod/uploadDocument',
			UPLOAD_DOCUMENT_REACT: 'https://21vyk11t77.execute-api.us-east-1.amazonaws.com/Prod/uploadDocumentreact',
			UPLOAD_CRED: 'https://21vyk11t77.execute-api.us-east-1.amazonaws.com/Prod/uploadCread',
			UPLOAD_FINAL_REPORT: 'https://2yu5mrxve4.execute-api.us-east-1.amazonaws.com/Prod/uploadFinalExamReport2',
			UPLOAD_FINAL_REPORT_REACT:
				'https://2yu5mrxve4.execute-api.us-east-1.amazonaws.com/Prod/uploadFinalExamReportreact',
			GET_FINAL_REPORT: 'https://2yu5mrxve4.execute-api.us-east-1.amazonaws.com/Prod/viewFinalReport',
			TECH_HOLD: 'https://q0480qwlcb.execute-api.us-east-1.amazonaws.com/Prod/techhold',
			BULK_UPLOAD_DOCUMENT: 'https://21vyk11t77.execute-api.us-east-1.amazonaws.com/Prod/bulkuploadDocument',
			BULK_UPLOAD_DOCUMENT_REACT: 'https://21vyk11t77.execute-api.us-east-1.amazonaws.com/Prod/bulkuploadreact',
			GENERATE_REPORTS: 'https://le1we4r3mh.execute-api.us-east-1.amazonaws.com/Prod/generateZip',
			REQUEST_ACCESS: 'https://le1we4r3mh.execute-api.us-east-1.amazonaws.com/Prod/newRequestAccess',
			GET_REQUEST_ALERTS: 'https://le1we4r3mh.execute-api.us-east-1.amazonaws.com/Prod/getRequestAlerts',
			UPDATE_VIEW_ALERT: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/savedViewedRequest',
			NOTE_ACTIONS: 'https://mn6eeos3zi.execute-api.us-east-1.amazonaws.com/Prod/notesActions',
			GENERATE_IMAGES: 'https://le1we4r3mh.execute-api.us-east-1.amazonaws.com/Prod/getDicomeImages',
			VERIFICATION_SHEET_DATA:
				'https://klt06j699f.execute-api.us-east-1.amazonaws.com/Prod/viewVarificationSheet',
			GET_PATIENT_BY_EMAIL: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getPatientByEmail',
			SET_STARRED_PATIENT: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/setstarredPatient',
			GET_STARRED_PATIENTS:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getAllstarredPatientData',
			SET_RECENT_SEARCHED_PATIENT:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/setRecentSearchedPatient',
			REMOVE_RECENT_SEARCHED_PATIENT:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/removetRecentSearchedPatient',
			GET_RECENT_SEARCHED_PATIENT:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getAllRecentSearchPatientdata',
			GET_RECENT_AND_STARRED_PATIENT_COUNT:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getCountOfPatientsearchAndstared',
			PATIENT_SEARCH_WITH_FILTER: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/searchPatientList',
			GET_REFERRER_USER: 'https://69i7l8aofg.execute-api.us-east-1.amazonaws.com/Prod/searchReferrerUser',
			GET_REFERRER_USER_LIST: 'https://69i7l8aofg.execute-api.us-east-1.amazonaws.com/Prod/ReferrerUserlist',
			GET_REFERRER_COMPONEY_LIST:
				'https://69i7l8aofg.execute-api.us-east-1.amazonaws.com/Prod/referrerComponyList',
			SHOW_PASSWORD: 'https://69i7l8aofg.execute-api.us-east-1.amazonaws.com/Prod/showPassword',
			GET_INSURANCE_FORM_DATA:
				'https://fb9ntwyw5a.execute-api.us-east-1.amazonaws.com/Prod/getInsurancePageFormData',
			GET_INSURANCE_DATA_BY_PID:
				'https://fb9ntwyw5a.execute-api.us-east-1.amazonaws.com/Prod/getInsurancePageDataByPid',
			ADD_PERMISSON: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/addPermission',
			ADD_SINGLE_PERMISSON: 'https://mzh1pxlhj3.execute-api.us-east-1.amazonaws.com/Prod/addSinglePermission',
			GET_PERMISSON_BY_USER_TYPE:
				'https://mzh1pxlhj3.execute-api.us-east-1.amazonaws.com/Prod/getPermissionDataByUserType',
			GET_ALL_USER_TYPE: 'https://mzh1pxlhj3.execute-api.us-east-1.amazonaws.com/Prod/getAlluserType',
			DELETE_USER_TYPE: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/deleteUsertype',
			UPDATE_USER_TYPE: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/updateusertype',
			ADD_USER_TYPE: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/addUserType',
			GET_TASK_ACTION: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/taskAction',
			COMPLETE_TASK: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/completeTask',
			GET_AND_SAVE_ALERTS: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/getAndSaveAlerts',
			GET_PAYMENT_DETAIL: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/getpaymnetDetail',
			DELETE_PAYMENT_DATA: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/deletepaymentdata',
			SAVE_PAYMENT_DATA: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/savePaymentdata',
			SAVE_INSURANCE_DATA: 'https://fb9ntwyw5a.execute-api.us-east-1.amazonaws.com/Prod/saveInsuranseData',
			GET_ATTORNEY: 'https://mc4p9pinv8.execute-api.us-east-1.amazonaws.com/Prod/getAttorney',
			GET_PAPERWORK_QUESTIONS: 'https://ogm6y0z6sg.execute-api.us-east-1.amazonaws.com/Prod/getQuestions',
			SEARCH_ATTORNEY: 'https://mc4p9pinv8.execute-api.us-east-1.amazonaws.com/Prod/searchAttorney',
			UPDATE_ATTORNEY: 'https://mc4p9pinv8.execute-api.us-east-1.amazonaws.com/Prod/editAttorney',
			DELETE_ATTORNEY: 'https://mc4p9pinv8.execute-api.us-east-1.amazonaws.com/Prod/deleteAttorney',
			GET_ALL_PLACEHOLDER: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/getPlaceHolers',
			TASK_ACTIONS: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/taskManagement',
			// GET_MODALITIES: "https://9joywugoc0.execute-api.us-east-1.amazonaws.com/Prod/getModalities",
			GET_PAYER_TYPE: 'https://9joywugoc0.execute-api.us-east-1.amazonaws.com/Prod/payertypeList',
			SAVE_QUESTION: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/saveQuestion',
			GET_QUESTIONS: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/getQuestion',
			// Alert Management APIs
			ASSIGNEDALERTSLIST: 'https://8gjs4vaqrg.execute-api.us-east-1.amazonaws.com/Prod/getAssignedAlerts',
			ASSIGNEDALLERTSCOUNT: 'https://8gjs4vaqrg.execute-api.us-east-1.amazonaws.com/Prod/assignedAlertsCount',
			AM_GETALERTS: 'https://8gjs4vaqrg.execute-api.us-east-1.amazonaws.com/Prod/getAlert',
			ALERT_ACTIONS: 'https://8gjs4vaqrg.execute-api.us-east-1.amazonaws.com/Prod/alertManagement',
			// modality apis
			GET_MODALITIES: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/GetAllModality',
			GET_LOCATION: ' https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/GetLocation',
			GET_MODALITY_DROPDOWN: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/GetModalityDropDown',
			CREATE_MODALITY: 'https://dj8ghieaj6.execute-api.us-east-1.amazonaws.com/Prod/CreateModality',
			UPDATE_MODALITY: 'https://jtzhoideaa.execute-api.us-east-1.amazonaws.com/Prod/EditModality',
			CHANGESTATUS: 'https://jtzhoideaa.execute-api.us-east-1.amazonaws.com/Prod/StatusChange',
			DELETE_MODALITY: 'https://jtzhoideaa.execute-api.us-east-1.amazonaws.com/Prod/DeleteModality',
			// exam apis
			GET_ALL_EXAMS: 'https://zvq2tbxt8i.execute-api.us-east-1.amazonaws.com/Prod/GetAllExam',
			CREATE_EXAM: ' https://zvq2tbxt8i.execute-api.us-east-1.amazonaws.com/Prod/CreateExam',
			UPDATE_EXAM: 'https://zvq2tbxt8i.execute-api.us-east-1.amazonaws.com/Prod/EditExam',
			// GET_MODALITIES: "https://9joywugoc0.execute-api.us-east-1.amazonaws.com/Prod/getModalities",
			GET_PAYER_TYPE: 'https://9joywugoc0.execute-api.us-east-1.amazonaws.com/Prod/payertypeList',
			SAVE_QUESTION: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/saveQuestion',
			UPDATE_QUESTION: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/updateQuestion',
			GET_QUESTIONS: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/getQuestion',
			GET_EXAM_REASONS_LIST: 'https://9sf4657usc.execute-api.us-east-1.amazonaws.com/Prod/getcancelReasonesList',
			CANCEL_EXAM: 'https://9sf4657usc.execute-api.us-east-1.amazonaws.com/Prod/cancelExam',
			CANCEL_EXAM_REVERT: 'https://9sf4657usc.execute-api.us-east-1.amazonaws.com/Prod/cancelExamrevert',
			CANCELEXAMREASONS: 'https://zgsbkb8nmf.execute-api.us-east-1.amazonaws.com/Prod/getcancelReasonesdev',
			CREATECANCELREASON: 'https://zgsbkb8nmf.execute-api.us-east-1.amazonaws.com/Prod/addCancelExamReasondev',
			EDITCANCELREASON: 'https://zgsbkb8nmf.execute-api.us-east-1.amazonaws.com/Prod/editCancelExamReasondev',
			GETALLDOCUMENTS: 'https://lo66l03g8f.execute-api.us-east-1.amazonaws.com/Prod/getAllDocumentdev',
			GETALLAUDIT: 'https://lo66l03g8f.execute-api.us-east-1.amazonaws.com/Prod/getAllAuditbyEid',
			FAXAGECRED: ' https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/getFaxagCred',
			GETTASKS: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/getTask',
			GETALERTS: 'https://00yggto744.execute-api.us-east-1.amazonaws.com/Prod/getAlert',
			GETEXAMBYMODALITY: 'https://ir5937uzje.execute-api.us-east-1.amazonaws.com/Prod/getExamsbyModality',
			GETRADIOLOGIST: 'https://ir5937uzje.execute-api.us-east-1.amazonaws.com/Prod/getRadiologist',
			GETREFERRER: 'https://ir5937uzje.execute-api.us-east-1.amazonaws.com/Prod/getRefferers',
			GETALERTBYEXAM: 'https://00yggto744.execute-api.us-east-1.amazonaws.com/Prod/getAndSaveAlerts',
			GETTASKSBYEXAM: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/taskAction',
			GETRECENTSEXAMS: 'https://ir5937uzje.execute-api.us-east-1.amazonaws.com/Prod/getRecentsExams',
			GETEXAMDETAILS: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/getExamDetails',
			EDITEXAM: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/editExam',
			VERIFY_PAPERWORK: 'https://mtirlx7am0.execute-api.us-east-1.amazonaws.com/Prod/varifyandgetpaperworkform',
			SAVE_SIGNATURE: 'https://ogm6y0z6sg.execute-api.us-east-1.amazonaws.com/Prod/saveSignature',
			SAVE_PAPERWORK: 'https://mtirlx7am0.execute-api.us-east-1.amazonaws.com/Prod/savepaperworkattechment',
			ADD_AUDIT: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/AddAudit',
			GET_ADUDITFAX: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/GetAuditByFax',
			SEND_FAX: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/SendFax',
			NO_SHOW_GRAPH: 'https://34459y5f3c.execute-api.us-east-1.amazonaws.com/no-show-graph',
			SAVE_QUESTION_ANS: 'https://mtirlx7am0.execute-api.us-east-1.amazonaws.com/Prod/saveQuestionAnsWer',
			SAVE_FORM_ORDER: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/orderForm',
			FAXAGEAPI: 'https://api.faxage.com/httpsfax.php',
			INSURANCECOMPANYTYPES:
				'https://5536ump333.execute-api.us-east-1.amazonaws.com/Prod/getInsuranceCompanyTypes',
			SEARCH_INSURANCE_COMPANY:
				'https://5536ump333.execute-api.us-east-1.amazonaws.com/Prod/searchInsuranceCompany',
			SEARCH_PATIENTS_DETAILS: 'https://t0md8gyl0k.execute-api.us-east-1.amazonaws.com/Prod/searchPatientsDetail',
			GET_SINGLE_AUDIT_DETAILS:
				'https://t0md8gyl0k.execute-api.us-east-1.amazonaws.com/Prod/getSingleAuditDetails',
			GET_AUDITS_FOR_USER: 'https://t0md8gyl0k.execute-api.us-east-1.amazonaws.com/Prod/getAuditsForUser',
			UPDATE_EXAM_FIRST: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/updateExamDetailsFirst',
			UPDATE_EXAM_SECOND: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/UpdateExamDetailsSecond',
			ADD_EXAM_TASKS: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/AddTasks',
			INSERT_TOKEN_DB: 'https://yl4qt9q7d4.execute-api.us-east-1.amazonaws.com/Prod/login',
			EXAM_MGT: 'https://niwakdocb7.execute-api.us-east-1.amazonaws.com/Prod/ExamMgt',
			TIMELINE: 'https://neyhmdxnb7.execute-api.us-east-1.amazonaws.com/Prod/Timeline',
			CANCEL_EXAM_Dot_Net: 'https://neyhmdxnb7.execute-api.us-east-1.amazonaws.com/Prod/Timeline',
		};
		break;
	case 'staging':
		API_URL = {
			HOMESCREEN_DATA: 'https://9gvkxrrfki.execute-api.us-east-1.amazonaws.com/Prod/getHomescreenData',
			LOGIN: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/login`,
			CREATE_NOTE: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/noteboard`,
			UPDATE_NOTE: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/noteboard`,
			REMOVE_NOTE: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/remove-note`,
			GET_NOTES: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/noteboard`,
			GET_NOTELABELS: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/notelabels`,
			SAVE_NOTELABELS: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/notelabels`,
			PATIENT_SEARCH: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/patientSearch',
			PATIENT_BY_ID: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/getPatient',
			GET_ALL_CITY: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getAllCityList',
			OPENTASKSLIST: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/openTasks',
			COMPLETE_TASKS: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/completeBulkTasks',
			// GET_PATIENT_DOCUMENT:
			// 'https://lo66l03g8f.execute-api.us-east-1.amazonaws.com/Prod/getPatientTimelineDatadev',
			GET_PATIENT_DOCUMENT:
				'https://udwa9duxej.execute-api.us-east-1.amazonaws.com/Prod/GetPatientTimeline',
			// GET_FINALIZED_EXAM: 'https://x33y1uevyk.execute-api.us-east-1.amazonaws.com/Prod/getfinalizedExam',
			ADD_PATIENT: 'https://6wciednm8i.execute-api.us-east-1.amazonaws.com/Prod/addPatientInfo',
			UPDATE_PATIENT: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/updatePtientInfo',
			RESET_PATIENT_PASSWORD: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/resetPatientPass',
			PATIENT_PORTAL_DATA: 'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/patientPortalData',
			SEND_PATIENT_PORTAL_ACCESS:
				'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/sendPatientAccessMail',
			GET_DOCUMENT_TYPE: 'https://y9nxinpfc8.execute-api.us-east-1.amazonaws.com/Prod/getDocumentList',
			UPLOAD_CRED: 'https://y9nxinpfc8.execute-api.us-east-1.amazonaws.com/Prod/uploadCread',
			UPLOAD_FINAL_REPORT: 'https://2yu5mrxve4.execute-api.us-east-1.amazonaws.com/Prod/uploadFinalExamReport2',
			UPLOAD_FINAL_REPORT_REACT:
				'https://2yu5mrxve4.execute-api.us-east-1.amazonaws.com/Prod/uploadFinalExamReportreact',
			GET_FINAL_REPORT: 'https://2yu5mrxve4.execute-api.us-east-1.amazonaws.com/Prod/viewFinalReport',
			TECH_HOLD: 'https://q0480qwlcb.execute-api.us-east-1.amazonaws.com/Prod/techhold',
			GENERATE_REPORTS: 'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/generateZip',
			REQUEST_ACCESS: 'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/newRequestAccess',
			GET_REQUEST_ALERTS: 'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/getRequestAlerts',
			UPDATE_VIEW_ALERT: 'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/savedViewedRequest',
			NOTE_ACTIONS: 'https://mn6eeos3zi.execute-api.us-east-1.amazonaws.com/Prod/notesActions',
			GENERATE_IMAGES: 'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/getDicomeImages',
			VERIFICATION_SHEET_DATA:
				'https://klt06j699f.execute-api.us-east-1.amazonaws.com/Prod/viewVarificationSheet',
			GET_PATIENT_BY_EMAIL: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getPatientByEmail',
			SET_STARRED_PATIENT: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/setstarredPatient',
			GET_STARRED_PATIENTS:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getAllstarredPatientData',
			SET_RECENT_SEARCHED_PATIENT:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/setRecentSearchedPatient',
			REMOVE_RECENT_SEARCHED_PATIENT:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/removetRecentSearchedPatient',
			GET_RECENT_SEARCHED_PATIENT:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getAllRecentSearchPatientdata',
			GET_RECENT_AND_STARRED_PATIENT_COUNT:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getCountOfPatientsearchAndstared',
			PATIENT_SEARCH_WITH_FILTER: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/searchPatientList',
			GET_REFERRER_USER: 'https://69i7l8aofg.execute-api.us-east-1.amazonaws.com/Prod/searchReferrerUser',
			GET_REFERRER_USER_LIST: 'https://69i7l8aofg.execute-api.us-east-1.amazonaws.com/Prod/ReferrerUserlist',
			GET_REFERRER_COMPONEY_LIST:
				'https://69i7l8aofg.execute-api.us-east-1.amazonaws.com/Prod/referrerComponyList',
			SHOW_PASSWORD: 'https://69i7l8aofg.execute-api.us-east-1.amazonaws.com/Prod/showPassword',
			GET_INSURANCE_FORM_DATA:
				'https://fb9ntwyw5a.execute-api.us-east-1.amazonaws.com/Prod/getInsurancePageFormData',
			GET_INSURANCE_DATA_BY_PID:
				'https://fb9ntwyw5a.execute-api.us-east-1.amazonaws.com/Prod/getInsurancePageDataByPid',
			ADD_PERMISSON: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/addPermission',
			ADD_SINGLE_PERMISSON: 'https://mzh1pxlhj3.execute-api.us-east-1.amazonaws.com/Prod/addSinglePermission',
			GET_PERMISSON_BY_USER_TYPE:
				'https://mzh1pxlhj3.execute-api.us-east-1.amazonaws.com/Prod/getPermissionDataByUserType',
			GET_ALL_USER_TYPE: 'https://mzh1pxlhj3.execute-api.us-east-1.amazonaws.com/Prod/getAlluserType',
			DELETE_USER_TYPE: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/deleteUsertype',
			UPDATE_USER_TYPE: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/updateusertype',
			ADD_USER_TYPE: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/addUserType',
			GET_TASK_ACTION: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/taskAction',
			COMPLETE_TASK: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/completeTask',
			GET_AND_SAVE_ALERTS: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/getAndSaveAlerts',
			GET_PAYMENT_DETAIL: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/getpaymnetDetail',
			DELETE_PAYMENT_DATA: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/deletepaymentdata',
			SAVE_PAYMENT_DATA: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/savePaymentdata',
			SAVE_INSURANCE_DATA: 'https://fb9ntwyw5a.execute-api.us-east-1.amazonaws.com/Prod/saveInsuranseData',
			GET_ATTORNEY: 'https://mc4p9pinv8.execute-api.us-east-1.amazonaws.com/Prod/getAttorney',
			GET_PAPERWORK_QUESTIONS: 'https://ogm6y0z6sg.execute-api.us-east-1.amazonaws.com/Prod/getQuestions',
			SEARCH_ATTORNEY: 'https://mc4p9pinv8.execute-api.us-east-1.amazonaws.com/Prod/searchAttorney',
			UPDATE_ATTORNEY: 'https://mc4p9pinv8.execute-api.us-east-1.amazonaws.com/Prod/editAttorney',
			DELETE_ATTORNEY: 'https://mc4p9pinv8.execute-api.us-east-1.amazonaws.com/Prod/deleteAttorney',
			GET_ALL_PLACEHOLDER: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/getPlaceHolers',
			TASK_ACTIONS: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/taskManagement',
			// GET_MODALITIES: "https://9joywugoc0.execute-api.us-east-1.amazonaws.com/Prod/getModalities",
			GET_PAYER_TYPE: 'https://9joywugoc0.execute-api.us-east-1.amazonaws.com/Prod/payertypeList',
			SAVE_QUESTION: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/saveQuestion',
			GET_QUESTIONS: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/getQuestion',
			// Alert Management APIs
			ASSIGNEDALERTSLIST: 'https://8gjs4vaqrg.execute-api.us-east-1.amazonaws.com/Prod/getAssignedAlerts',
			ASSIGNEDALLERTSCOUNT: 'https://8gjs4vaqrg.execute-api.us-east-1.amazonaws.com/Prod/assignedAlertsCount',
			AM_GETALERTS: 'https://8gjs4vaqrg.execute-api.us-east-1.amazonaws.com/Prod/getAlert',
			ALERT_ACTIONS: 'https://8gjs4vaqrg.execute-api.us-east-1.amazonaws.com/Prod/alertManagement',
			// modality apis
			GET_MODALITIES: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/GetAllModality',
			GET_LOCATION: ' https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/GetLocation',
			GET_MODALITY_DROPDOWN: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/GetModalityDropDown',
			CREATE_MODALITY: 'https://dj8ghieaj6.execute-api.us-east-1.amazonaws.com/Prod/CreateModality',
			UPDATE_MODALITY: 'https://jtzhoideaa.execute-api.us-east-1.amazonaws.com/Prod/EditModality',
			CHANGESTATUS: 'https://jtzhoideaa.execute-api.us-east-1.amazonaws.com/Prod/StatusChange',
			DELETE_MODALITY: 'https://jtzhoideaa.execute-api.us-east-1.amazonaws.com/Prod/DeleteModality',
			// exam apis
			GET_ALL_EXAMS: 'https://zvq2tbxt8i.execute-api.us-east-1.amazonaws.com/Prod/GetAllExam',
			CREATE_EXAM: ' https://zvq2tbxt8i.execute-api.us-east-1.amazonaws.com/Prod/CreateExam',
			UPDATE_EXAM: 'https://zvq2tbxt8i.execute-api.us-east-1.amazonaws.com/Prod/EditExam',
			// GET_MODALITIES: "https://9joywugoc0.execute-api.us-east-1.amazonaws.com/Prod/getModalities",
			GET_PAYER_TYPE: 'https://9joywugoc0.execute-api.us-east-1.amazonaws.com/Prod/payertypeList',
			SAVE_QUESTION: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/saveQuestion',
			UPDATE_QUESTION: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/updateQuestion',
			GET_QUESTIONS: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/getQuestion',
			GET_EXAM_REASONS_LIST: 'https://01kda3vxid.execute-api.us-east-1.amazonaws.com/Prod/getcancelReasonesList',
			CANCEL_EXAM: 'https://01kda3vxid.execute-api.us-east-1.amazonaws.com/Prod/cancelExam',
			CANCEL_EXAM_REVERT: 'https://01kda3vxid.execute-api.us-east-1.amazonaws.com/Prod/cancelExamrevert',
			CANCELEXAMREASONS: 'https://zgsbkb8nmf.execute-api.us-east-1.amazonaws.com/Prod/getcancelReasonesdev',
			CREATECANCELREASON: 'https://zgsbkb8nmf.execute-api.us-east-1.amazonaws.com/Prod/addCancelExamReasondev',
			EDITCANCELREASON: 'https://zgsbkb8nmf.execute-api.us-east-1.amazonaws.com/Prod/editCancelExamReasondev',
			GETALLDOCUMENTS: 'https://lo66l03g8f.execute-api.us-east-1.amazonaws.com/Prod/getAllDocumentdev',
			GETALLAUDIT: 'https://lo66l03g8f.execute-api.us-east-1.amazonaws.com/Prod/getAllAuditbyEid',
			FAXAGECRED: ' https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/getFaxagCred',
			GETTASKS: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/getTask',
			GETALERTS: 'https://00yggto744.execute-api.us-east-1.amazonaws.com/Prod/getAlert',
			GETEXAMBYMODALITY: 'https://ir5937uzje.execute-api.us-east-1.amazonaws.com/Prod/getExamsbyModality',
			GETRADIOLOGIST: 'https://ir5937uzje.execute-api.us-east-1.amazonaws.com/Prod/getRadiologist',
			GETREFERRER: 'https://ir5937uzje.execute-api.us-east-1.amazonaws.com/Prod/getRefferers',
			GETALERTBYEXAM: 'https://00yggto744.execute-api.us-east-1.amazonaws.com/Prod/getAndSaveAlerts',
			GETTASKSBYEXAM: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/taskAction',
			GETRECENTSEXAMS: 'https://ir5937uzje.execute-api.us-east-1.amazonaws.com/Prod/getRecentsExams',
			GETEXAMDETAILS: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/getExamDetails',
			EDITEXAM: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/editExam',
			VERIFY_PAPERWORK: 'https://mtirlx7am0.execute-api.us-east-1.amazonaws.com/Prod/varifyandgetpaperworkform',
			SAVE_SIGNATURE: 'https://ogm6y0z6sg.execute-api.us-east-1.amazonaws.com/Prod/saveSignature',
			SAVE_PAPERWORK: 'https://mtirlx7am0.execute-api.us-east-1.amazonaws.com/Prod/savepaperworkattechment',
			ADD_AUDIT: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/AddAudit',
			GET_ADUDITFAX: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/GetAuditByFax',
			SEND_FAX: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/SendFax',
			NO_SHOW_GRAPH: 'https://34459y5f3c.execute-api.us-east-1.amazonaws.com/no-show-graph',
			SAVE_QUESTION_ANS: 'https://mtirlx7am0.execute-api.us-east-1.amazonaws.com/Prod/saveQuestionAnsWer',
			SAVE_FORM_ORDER: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/orderForm',
			FAXAGEAPI: 'https://api.faxage.com/httpsfax.php',
			INSURANCECOMPANYTYPES:
				'https://5536ump333.execute-api.us-east-1.amazonaws.com/Prod/getInsuranceCompanyTypes',
			SEARCH_INSURANCE_COMPANY:
				'https://5536ump333.execute-api.us-east-1.amazonaws.com/Prod/searchInsuranceCompany',
			SEARCH_PATIENTS_DETAILS: 'https://t0md8gyl0k.execute-api.us-east-1.amazonaws.com/Prod/searchPatientsDetail',
			GET_SINGLE_AUDIT_DETAILS:
				'https://t0md8gyl0k.execute-api.us-east-1.amazonaws.com/Prod/getSingleAuditDetails',
			GET_AUDITS_FOR_USER: 'https://t0md8gyl0k.execute-api.us-east-1.amazonaws.com/Prod/getAuditsForUser',
			UPDATE_EXAM_FIRST: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/updateExamDetailsFirst',
			UPDATE_EXAM_SECOND: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/UpdateExamDetailsSecond',
			ADD_EXAM_TASKS: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/AddTasks',
			INSERT_TOKEN_DB: 'https://yl4qt9q7d4.execute-api.us-east-1.amazonaws.com/Prod/login',
			EXAM_MGT: 'https://niwakdocb7.execute-api.us-east-1.amazonaws.com/Prod/ExamMgt',
			TIMELINE: 'https://neyhmdxnb7.execute-api.us-east-1.amazonaws.com/Prod/Timeline',
			CANCEL_EXAM_Dot_Net: 'https://neyhmdxnb7.execute-api.us-east-1.amazonaws.com/Prod/Timeline',
		};
		break;
	default:
		API_URL = {
			HOMESCREEN_DATA: 'https://9gvkxrrfki.execute-api.us-east-1.amazonaws.com/Prod/getHomescreenData',
			LOGIN: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/login`,
			CREATE_NOTE: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/noteboard`,
			UPDATE_NOTE: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/noteboard`,
			REMOVE_NOTE: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/remove-note`,
			GET_NOTES: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/noteboard`,
			GET_NOTELABELS: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/notelabels`,
			SAVE_NOTELABELS: `https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/notelabels`,
			PATIENT_SEARCH: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/patientSearch',
			PATIENT_BY_ID: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/getPatient',
			GET_ALL_CITY: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getAllCityList',
			OPENTASKSLIST: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/openTasks',
			COMPLETE_TASKS: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/completeBulkTasks',
			// GET_PATIENT_DOCUMENT: 'https://b1g1xdcrq8.execute-api.us-east-1.amazonaws.com/Prod/getPatientTimelineData',
			// GET_PATIENT_DOCUMENT:
			// 'https://lo66l03g8f.execute-api.us-east-1.amazonaws.com/Prod/getPatientTimelineDatadev',
			GET_PATIENT_DOCUMENT:
				'https://udwa9duxej.execute-api.us-east-1.amazonaws.com/Prod/GetPatientTimeline',
			// GET_FINALIZED_EXAM: 'https://x33y1uevyk.execute-api.us-east-1.amazonaws.com/Prod/getfinalizedExam',
			ADD_PATIENT: 'https://6wciednm8i.execute-api.us-east-1.amazonaws.com/Prod/addPatientInfo',
			UPDATE_PATIENT: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/updatePtientInfo',
			RESET_PATIENT_PASSWORD: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/resetPatientPass',
			PATIENT_PORTAL_DATA: 'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/patientPortalData',
			SEND_PATIENT_PORTAL_ACCESS:
				'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/sendPatientAccessMail',
			GET_DOCUMENT_TYPE: 'https://y9nxinpfc8.execute-api.us-east-1.amazonaws.com/Prod/getDocumentList',
			UPLOAD_CRED: 'https://y9nxinpfc8.execute-api.us-east-1.amazonaws.com/Prod/uploadCread',
			UPLOAD_FINAL_REPORT: 'https://2yu5mrxve4.execute-api.us-east-1.amazonaws.com/Prod/uploadFinalExamReport2',
			UPLOAD_FINAL_REPORT_REACT:
				'https://2yu5mrxve4.execute-api.us-east-1.amazonaws.com/Prod/uploadFinalExamReportreact',
			GET_FINAL_REPORT: 'https://2yu5mrxve4.execute-api.us-east-1.amazonaws.com/Prod/viewFinalReport',
			TECH_HOLD: 'https://q0480qwlcb.execute-api.us-east-1.amazonaws.com/Prod/techhold',
			GENERATE_REPORTS: 'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/generateZip',
			REQUEST_ACCESS: 'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/newRequestAccess',
			GET_REQUEST_ALERTS: 'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/getRequestAlerts',
			UPDATE_VIEW_ALERT: 'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/savedViewedRequest',
			NOTE_ACTIONS: 'https://mn6eeos3zi.execute-api.us-east-1.amazonaws.com/Prod/notesActions',
			GENERATE_IMAGES: 'https://0aqj63watd.execute-api.us-east-1.amazonaws.com/Prod/getDicomeImages',
			VERIFICATION_SHEET_DATA:
				'https://klt06j699f.execute-api.us-east-1.amazonaws.com/Prod/viewVarificationSheet',
			GET_PATIENT_BY_EMAIL: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getPatientByEmail',
			SET_STARRED_PATIENT: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/setstarredPatient',
			GET_STARRED_PATIENTS:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getAllstarredPatientData',
			SET_RECENT_SEARCHED_PATIENT:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/setRecentSearchedPatient',
			REMOVE_RECENT_SEARCHED_PATIENT:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/removetRecentSearchedPatient',
			GET_RECENT_SEARCHED_PATIENT:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getAllRecentSearchPatientdata',
			GET_RECENT_AND_STARRED_PATIENT_COUNT:
				'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/getCountOfPatientsearchAndstared',
			PATIENT_SEARCH_WITH_FILTER: 'https://7mu3ub6edd.execute-api.us-east-1.amazonaws.com/Prod/searchPatientList',
			GET_REFERRER_USER: 'https://69i7l8aofg.execute-api.us-east-1.amazonaws.com/Prod/searchReferrerUser',
			GET_REFERRER_USER_LIST: 'https://69i7l8aofg.execute-api.us-east-1.amazonaws.com/Prod/ReferrerUserlist',
			GET_REFERRER_COMPONEY_LIST:
				'https://69i7l8aofg.execute-api.us-east-1.amazonaws.com/Prod/referrerComponyList',
			SHOW_PASSWORD: 'https://69i7l8aofg.execute-api.us-east-1.amazonaws.com/Prod/showPassword',
			GET_INSURANCE_FORM_DATA:
				'https://fb9ntwyw5a.execute-api.us-east-1.amazonaws.com/Prod/getInsurancePageFormData',
			GET_INSURANCE_DATA_BY_PID:
				'https://fb9ntwyw5a.execute-api.us-east-1.amazonaws.com/Prod/getInsurancePageDataByPid',
			ADD_PERMISSON: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/addPermission',
			ADD_SINGLE_PERMISSON: 'https://mzh1pxlhj3.execute-api.us-east-1.amazonaws.com/Prod/addSinglePermission',
			GET_PERMISSON_BY_USER_TYPE:
				'https://mzh1pxlhj3.execute-api.us-east-1.amazonaws.com/Prod/getPermissionDataByUserType',
			GET_ALL_USER_TYPE: 'https://mzh1pxlhj3.execute-api.us-east-1.amazonaws.com/Prod/getAlluserType',
			DELETE_USER_TYPE: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/deleteUsertype',
			UPDATE_USER_TYPE: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/updateusertype',
			ADD_USER_TYPE: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/addUserType',
			GET_TASK_ACTION: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/taskAction',
			COMPLETE_TASK: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/completeTask',
			GET_AND_SAVE_ALERTS: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/getAndSaveAlerts',
			GET_PAYMENT_DETAIL: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/getpaymnetDetail',
			DELETE_PAYMENT_DATA: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/deletepaymentdata',
			SAVE_PAYMENT_DATA: 'https://1nauaudzb9.execute-api.us-east-1.amazonaws.com/dev/v1/savePaymentdata',
			SAVE_INSURANCE_DATA: 'https://fb9ntwyw5a.execute-api.us-east-1.amazonaws.com/Prod/saveInsuranseData',
			GET_ATTORNEY: 'https://mc4p9pinv8.execute-api.us-east-1.amazonaws.com/Prod/getAttorney',
			GET_PAPERWORK_QUESTIONS: 'https://ogm6y0z6sg.execute-api.us-east-1.amazonaws.com/Prod/getQuestions',
			SEARCH_ATTORNEY: 'https://mc4p9pinv8.execute-api.us-east-1.amazonaws.com/Prod/searchAttorney',
			UPDATE_ATTORNEY: 'https://mc4p9pinv8.execute-api.us-east-1.amazonaws.com/Prod/editAttorney',
			DELETE_ATTORNEY: 'https://mc4p9pinv8.execute-api.us-east-1.amazonaws.com/Prod/deleteAttorney',
			GET_ALL_PLACEHOLDER: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/getPlaceHolers',
			TASK_ACTIONS: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/taskManagement',
			// Alert Management APIs
			ASSIGNEDALERTSLIST: 'https://8gjs4vaqrg.execute-api.us-east-1.amazonaws.com/Prod/getAssignedAlerts',
			ASSIGNEDALLERTSCOUNT: 'https://8gjs4vaqrg.execute-api.us-east-1.amazonaws.com/Prod/assignedAlertsCount',
			AM_GETALERTS: 'https://8gjs4vaqrg.execute-api.us-east-1.amazonaws.com/Prod/getAlert',
			ALERT_ACTIONS: 'https://8gjs4vaqrg.execute-api.us-east-1.amazonaws.com/Prod/alertManagement',
			// GET_MODALITIES: "https://9joywugoc0.execute-api.us-east-1.amazonaws.com/Prod/getModalities",
			GET_PAYER_TYPE: 'https://9joywugoc0.execute-api.us-east-1.amazonaws.com/Prod/payertypeList',
			SAVE_QUESTION: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/saveQuestion',
			GET_QUESTIONS: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/getQuestion',
			// modality apis
			GET_MODALITIES: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/GetAllModality',
			GET_LOCATION: ' https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/GetLocation',
			GET_MODALITY_DROPDOWN: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/GetModalityDropDown',
			CREATE_MODALITY: 'https://dj8ghieaj6.execute-api.us-east-1.amazonaws.com/Prod/CreateModality',
			UPDATE_MODALITY: 'https://jtzhoideaa.execute-api.us-east-1.amazonaws.com/Prod/EditModality',
			CHANGESTATUS: 'https://jtzhoideaa.execute-api.us-east-1.amazonaws.com/Prod/StatusChange',
			DELETE_MODALITY: 'https://jtzhoideaa.execute-api.us-east-1.amazonaws.com/Prod/DeleteModality',
			// exam apis
			GET_ALL_EXAMS: 'https://zvq2tbxt8i.execute-api.us-east-1.amazonaws.com/Prod/GetAllExam',
			CREATE_EXAM: ' https://zvq2tbxt8i.execute-api.us-east-1.amazonaws.com/Prod/CreateExam',
			UPDATE_EXAM: 'https://zvq2tbxt8i.execute-api.us-east-1.amazonaws.com/Prod/EditExam',
			// GET_MODALITIES: "https://9joywugoc0.execute-api.us-east-1.amazonaws.com/Prod/getModalities",
			GET_PAYER_TYPE: 'https://9joywugoc0.execute-api.us-east-1.amazonaws.com/Prod/payertypeList',
			SAVE_QUESTION: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/saveQuestion',
			UPDATE_QUESTION: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/updateQuestion',
			GET_QUESTIONS: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/getQuestion',
			GET_EXAM_REASONS_LIST: 'https://01kda3vxid.execute-api.us-east-1.amazonaws.com/Prod/getcancelReasonesList',
			CANCEL_EXAM: 'https://01kda3vxid.execute-api.us-east-1.amazonaws.com/Prod/cancelExam',
			CANCEL_EXAM_REVERT: 'https://01kda3vxid.execute-api.us-east-1.amazonaws.com/Prod/cancelExamrevert',
			CANCELEXAMREASONS: 'https://zgsbkb8nmf.execute-api.us-east-1.amazonaws.com/Prod/getcancelReasonesdev',
			CREATECANCELREASON: 'https://zgsbkb8nmf.execute-api.us-east-1.amazonaws.com/Prod/addCancelExamReasondev',
			EDITCANCELREASON: 'https://zgsbkb8nmf.execute-api.us-east-1.amazonaws.com/Prod/editCancelExamReasondev',
			GETALLDOCUMENTS: 'https://lo66l03g8f.execute-api.us-east-1.amazonaws.com/Prod/getAllDocumentdev',
			GETALLAUDIT: 'https://lo66l03g8f.execute-api.us-east-1.amazonaws.com/Prod/getAllAuditbyEid',
			FAXAGECRED: ' https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/getFaxagCred',
			GETTASKS: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/getTask',
			GETALERTS: 'https://00yggto744.execute-api.us-east-1.amazonaws.com/Prod/getAlert',
			GETEXAMBYMODALITY: 'https://ir5937uzje.execute-api.us-east-1.amazonaws.com/Prod/getExamsbyModality',
			GETRADIOLOGIST: 'https://ir5937uzje.execute-api.us-east-1.amazonaws.com/Prod/getRadiologist',
			GETREFERRER: 'https://ir5937uzje.execute-api.us-east-1.amazonaws.com/Prod/getRefferers',
			GETALERTBYEXAM: 'https://00yggto744.execute-api.us-east-1.amazonaws.com/Prod/getAndSaveAlerts',
			GETTASKSBYEXAM: 'https://25otc0z4z0.execute-api.us-east-1.amazonaws.com/Prod/taskAction',
			GETRECENTSEXAMS: 'https://ir5937uzje.execute-api.us-east-1.amazonaws.com/Prod/getRecentsExams',
			GETEXAMDETAILS: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/getExamDetails',
			EDITEXAM: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/editExam',
			VERIFY_PAPERWORK: 'https://mtirlx7am0.execute-api.us-east-1.amazonaws.com/Prod/varifyandgetpaperworkform',
			SAVE_SIGNATURE: 'https://ogm6y0z6sg.execute-api.us-east-1.amazonaws.com/Prod/saveSignature',
			SAVE_PAPERWORK: 'https://mtirlx7am0.execute-api.us-east-1.amazonaws.com/Prod/savepaperworkattechment',
			ADD_AUDIT: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/AddAudit',
			GET_ADUDITFAX: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/GetAuditByFax',
			SEND_FAX: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/SendFax',
			NO_SHOW_GRAPH: 'https://34459y5f3c.execute-api.us-east-1.amazonaws.com/no-show-graph',
			SAVE_QUESTION_ANS: 'https://mtirlx7am0.execute-api.us-east-1.amazonaws.com/Prod/saveQuestionAnsWer',
			SAVE_FORM_ORDER: 'https://3lnwjdziwb.execute-api.us-east-1.amazonaws.com/Prod/orderForm',
			// faxage api
			FAXAGEAPI: 'https://api.faxage.com/httpsfax.php',
			INSURANCECOMPANYTYPES:
				'https://5536ump333.execute-api.us-east-1.amazonaws.com/Prod/getInsuranceCompanyTypes',
			SEARCH_INSURANCE_COMPANY:
				'https://5536ump333.execute-api.us-east-1.amazonaws.com/Prod/searchInsuranceCompany',
			SEARCH_PATIENTS_DETAILS: 'https://t0md8gyl0k.execute-api.us-east-1.amazonaws.com/Prod/searchPatientsDetail',
			GET_SINGLE_AUDIT_DETAILS:
				'https://t0md8gyl0k.execute-api.us-east-1.amazonaws.com/Prod/getSingleAuditDetails',
			GET_AUDITS_FOR_USER: 'https://t0md8gyl0k.execute-api.us-east-1.amazonaws.com/Prod/getAuditsForUser',
			UPDATE_EXAM_FIRST: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/updateExamDetailsFirst',
			UPDATE_EXAM_SECOND: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/UpdateExamDetailsSecond',
			ADD_EXAM_TASKS: 'https://s8l10sjfq0.execute-api.us-east-1.amazonaws.com/Prod/AddTasks',
			INSERT_TOKEN_DB: 'https://yl4qt9q7d4.execute-api.us-east-1.amazonaws.com/Prod/login',
			EXAM_MGT: 'https://niwakdocb7.execute-api.us-east-1.amazonaws.com/Prod/ExamMgt',
			TIMELINE: 'https://neyhmdxnb7.execute-api.us-east-1.amazonaws.com/Prod/Timeline',
			CANCEL_EXAM_Dot_Net: 'https://neyhmdxnb7.execute-api.us-east-1.amazonaws.com/Prod/Timeline',
		};
}

const Permissions = {
	share_patient_access: 'share_patient_access',
	patient_lookup: 'patient_lookup',
	view_document: 'view_document',
	upload_document: 'upload_document',
	share_patient_access: 'share_patient_access',
	update_patient_dateail: 'update_patient_dateail',
	view_dashboard: 'view_dashboard',
	attorney_lookup: 'attorney_lookup',
	enterprise_analytics: 'enterprise_analytics',
	pre_schedule_status: 'pre_schedule_status',
	no_show_exams: 'no_show_exams',
	pending_interpretation: 'pending_interpretation',
	tech_hold: 'tech_hold',
	incoming_orders: 'incoming_orders',
	schedule: 'incoming_orders',
	completed_exams: 'completed_exams',
	finalized_reports: 'finalized_reports',
	delete_attorney: 'delete_attorney',
	update_attorney: 'update_attorney',
	update_modality: 'update_modality',
	delete_modality: 'delete_attorney',
	user_tech: 'Technician',
	companytypes: 'companytypes',
	update_insurance: 'update_insurance'
};

const CustomSettings = {
	BackURL: 'https://pom.radiologywork.com/home',
	CoockieDomain: '.radiologywork.com',
	// BackURL: 'http://pom.webflowonline.com/home',
	// CoockieDomain: '.webflowonline.com',
	IsProdDeployment: false
};

export {API_URL, Permissions, CustomSettings};
